#ifndef BFW_WINDOWS_Resources_hpp

#define BFW_WINDOWS_Resources_hpp



#define BFW_WINDOWS_VERSION_LIST 1, 0, 0, 0



#define BFW_WINDOWS_VERSION_STRING_A "1.0.0.0"
#define BFW_WINDOWS_VERSION_STRING_W L"1.0.0.0"

#ifdef _UNICODE

#define BFW_WINDOWS_VERSION_STRING BFW_WINDOWS_VERSION_STRING_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_VERSION_STRING BFW_WINDOWS_VERSION_STRING_A

#endif



#define BFW_WINDOWS_APP_NAME_A "BFW_WINDOWS"
#define BFW_WINDOWS_APP_NAME_W L"BFW_WINDOWS"

#ifdef _UNICODE

#define BFW_WINDOWS_APP_NAME BFW_WINDOWS_APP_NAME_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_APP_NAME BFW_WINDOWS_APP_NAME_A

#endif



#ifdef BFW_LINK_DYNAMIC

#define BFW_WINDOWS_FILE_NAME_A "BFW_WINDOWS_DYNAMIC.exe"
#define BFW_WINDOWS_FILE_NAME_W L"BFW_WINDOWS_DYNAMIC.exe"

#ifdef _UNICODE

#define BFW_WINDOWS_FILE_NAME BFW_WINDOWS_FILE_NAME_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_FILE_NAME BFW_WINDOWS_FILE_NAME_A

#endif

#endif

#ifdef BFW_LINK_STATIC

#define BFW_WINDOWS_FILE_NAME_A "BFW_WINDOWS_STATIC.exe"
#define BFW_WINDOWS_FILE_NAME_W L"BFW_WINDOWS_STATIC.exe"

#ifdef _UNICODE

#define BFW_WINDOWS_FILE_NAME BFW_WINDOWS_FILE_NAME_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_FILE_NAME BFW_WINDOWS_FILE_NAME_A

#endif

#endif



#define BFW_WINDOWS_COMPANY_NAME_A "BSW"
#define BFW_WINDOWS_COMPANY_NAME_W L"BSW"

#ifdef _UNICODE

#define BFW_WINDOWS_COMPANY_NAME BFW_WINDOWS_COMPANY_NAME_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_COMPANY_NAME BFW_WINDOWS_COMPANY_NAME_A

#endif



#define BFW_WINDOWS_COPY_RIGHT_EN_US_A "Copyright (C) BSW (TM). All rights reserved."
#define BFW_WINDOWS_COPY_RIGHT_EN_US_W L"Copyright © BSW™. All rights reserved."

#ifdef _UNICODE

#define BFW_WINDOWS_COPY_RIGHT_EN_US BFW_WINDOWS_COPY_RIGHT_EN_US_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_COPY_RIGHT_EN_US BFW_WINDOWS_COPY_RIGHT_EN_US_A

#endif



#define BFW_WINDOWS_MAIN_WINDOW_CLASS_A "BFW_WINDOWS_MainWindowClass"
#define BFW_WINDOWS_MAIN_WINDOW_CLASS_W L"BFW_WINDOWS_MainWindowClass"

#ifdef _UNICODE

#define BFW_WINDOWS_MAIN_WINDOW_CLASS BFW_WINDOWS_MAIN_WINDOW_CLASS_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_MAIN_WINDOW_CLASS BFW_WINDOWS_MAIN_WINDOW_CLASS_A

#endif




#define BFW_WINDOWS_CHILD_WINDOW_CLASS_A "BFW_WINDOWS_ChildWindowClass"
#define BFW_WINDOWS_CHILD_WINDOW_CLASS_W L"BFW_WINDOWS_ChildWindowClass"

#ifdef _UNICODE

#define BFW_WINDOWS_CHILD_WINDOW_CLASS BFW_WINDOWS_CHILD_WINDOW_CLASS_W

#endif

#ifndef _UNICODE

#define BFW_WINDOWS_CHILD_WINDOW_CLASS BFW_WINDOWS_CHILD_WINDOW_CLASS_A

#endif



#define BFW_WINDOWS_IDI_MAIN_ICON 1



#define BFW_WINDOWS_IDM_MAIN_MANIFEST 1



#endif
