@echo off

echo on

if "%SolutionDir%" == "" call ".\BFW_ESP32_Path.bat"

@echo off

pushd "%SolutionDir%"

set CompileFlags=-w -Os -Werror=return-type -DARDUINO_CORE_BUILD -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_ESP32S3_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD=\"ESP32S3_DEV\" -DARDUINO_VARIANT=\"esp32s3\" -DARDUINO_PARTITION_huge_app -DARDUINO_HOST_OS=\"windows\" -DARDUINO_FQBN=\"esp32:esp32:esp32s3:UploadSpeed=921600,USBMode=hwcdc,CDCOnBoot=cdc,MSCOnBoot=default,DFUOnBoot=dfu,UploadMode=default,CPUFreq=240,FlashMode=qio,FlashSize=16M,PartitionScheme=huge_app,DebugLevel=none,PSRAM=opi,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=builtin,ZigbeeMode=default\" -DESP32=ESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_RUNNING_CORE=1 -DARDUINO_EVENT_RUNNING_CORE=1 -DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MSC_ON_BOOT=0 -DARDUINO_USB_DFU_ON_BOOT=1 "@%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\flags\defines" -iprefix "%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\include\\" "@%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\flags\includes" "-I%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\qio_opi\include\\" "-I%ESPPack%hardware\esp32\3.2.0\cores\esp32\\" "-I%ESPPack%hardware\esp32\3.2.0\variants\esp32s3\\"
set CFlags="@%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\flags\c_flags"
set CPPFlags="@%ESPPack%tools\esp32-arduino-libs\idf-release_v5.4-2f7dcd86-v1\esp32s3\flags\cpp_flags"

if not exist ".\Solution Items\Dependencies\ArduinoCore\Lib\" mkdir ".\Solution Items\Dependencies\ArduinoCore\Lib\"

echo on

xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\ColorFormat.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\ColorFormat.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\IPAddress.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\IPAddress.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\FirmwareMSC.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\FirmwareMSC.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\Esp.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\Esp.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\HWCDC.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\HWCDC.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\HEXBuilder.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\HEXBuilder.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\HardwareSerial.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\HardwareSerial.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\FunctionalInterrupt.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\FunctionalInterrupt.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\MD5Builder.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\MD5Builder.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\MacAddress.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\MacAddress.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\Print.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\Print.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\SHA1Builder.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\SHA1Builder.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\Stream.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\Stream.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\StreamString.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\StreamString.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\Tone.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\Tone.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\USB.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\USB.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\USBCDC.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\USBCDC.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\USBMSC.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\USBMSC.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\WMath.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\WMath.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\WString.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\WString.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\base64.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\base64.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\cbuf.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\cbuf.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\chip-debug-report.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\chip-debug-report.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-adc.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-adc.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-bt.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-bt.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-cpu.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-cpu.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-dac.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-dac.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-gpio.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-gpio.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-i2c-ng.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c-ng.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-i2c-slave.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c-slave.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-i2c.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-ledc.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-ledc.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-matrix.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-matrix.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-misc.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-misc.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-periman.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-periman.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-psram.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-psram.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-rgb-led.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-rgb-led.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-sigmadelta.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-sigmadelta.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-spi.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-spi.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-time.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-time.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-timer.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-timer.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-tinyusb.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-tinyusb.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-touch-ng.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-touch-ng.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-touch.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-touch.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-uart.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-uart.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\firmware_msc_fat.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\firmware_msc_fat.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\freertos_stats.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\freertos_stats.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\libb64\cdecode.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\cdecode.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\libb64\cencode.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\cencode.o"
xtensa-esp32s3-elf-g++ %CompileFlags% %CPPFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\main.cpp" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\main.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\stdlib_noniso.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\stdlib_noniso.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\wiring_pulse.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\wiring_pulse.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\esp32-hal-rmt.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-rmt.o"
xtensa-esp32s3-elf-gcc %CompileFlags% %CFlags% -c "%ESPPack%hardware\esp32\3.2.0\cores\esp32\wiring_shift.c" -o ".\Solution Items\Dependencies\ArduinoCore\Lib\wiring_shift.o"

xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\ColorFormat.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\IPAddress.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\FirmwareMSC.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\Esp.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\HWCDC.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\HEXBuilder.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\HardwareSerial.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\FunctionalInterrupt.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\MD5Builder.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\MacAddress.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\Print.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\SHA1Builder.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\Stream.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\StreamString.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\Tone.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\USB.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\USBCDC.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\USBMSC.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\WMath.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\WString.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\base64.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\cbuf.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\chip-debug-report.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-adc.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-bt.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-cpu.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-dac.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-gpio.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c-ng.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c-slave.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-i2c.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-ledc.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-matrix.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-misc.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-periman.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-psram.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-rgb-led.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-sigmadelta.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-spi.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-time.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-timer.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-tinyusb.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-touch-ng.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-touch.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-uart.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\firmware_msc_fat.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\freertos_stats.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\cdecode.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\cencode.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\main.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\stdlib_noniso.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\wiring_pulse.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\esp32-hal-rmt.o"
xtensa-esp32s3-elf-ar rcs ".\Solution Items\Dependencies\ArduinoCore\Lib\ArduinoCore.a" ".\Solution Items\Dependencies\ArduinoCore\Lib\wiring_shift.o"

@echo off

set CompileFlags=
set CFlags=
set CPPFlags=

popd

echo on
